version: '3'
services:
  mysql:
    image: mysql:8.0.33
    container_name: kyudo_app
    environment:
      MYSQL_ROOT_PASSWORD: Ok010214
      MYSQL_DATABASE: kyudo_app
      MYSQL_USER: kotaro
      MYSQL_PASSWORD: Ok010214
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
volumes:
  mysql-data:

