@startuml

entity Place {
    INT(10) PlaceId
    VARCHAR(255) PlaceName
    VARCHAR(255) Address
}

entity BelongingGroup {
    INT(10) GroupId
    VARCHAR(20) Name
}

entity User {
    INT(10) UserId
    VARCHAR(10) Name
    VARCHAR(30) MailAddress
    TIMESTAMP CreateAt
    INT(10) LoreId
    INT(10) GroupId
}

entity GameMatch {
    INT MatchId
    DATE MatchDate
    INT PlaceId
    INT UserId
}

entity GameMatch_User {
    INT MatchId
    INT UserId
}

entity Recode {
    INT RecodeId
    INT UserId
    INT HitCount
    INT TotalShots
    TIMESTAMP CreateAt
}

entity Team {
    INT TeamId
    VARCHAR(10) TeamName
}

entity Team_User {
    INT UserId
    INT TeamId
}

User }|--|| BelongingGroup : "GroupId"
GameMatch }|--|| Place : "PlaceId"
GameMatch_User }|--|| GameMatch : "MatchId"
GameMatch_User }|--|| User : "UserId"
Recode }|--|| User : "UserId"
Team_User }|--|| User : "UserId"
Team_User }|--|| Team : "TeamId"

@enduml